//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 09:56:30 AM CST 
//


package king.flow.view;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for device_enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="device_enum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="magnetCard"/>
 *     &lt;enumeration value="ICCard"/>
 *     &lt;enumeration value="sensorCard"/>
 *     &lt;enumeration value="twoInOneCard"/>
 *     &lt;enumeration value="printer"/>
 *     &lt;enumeration value="keyboard"/>
 *     &lt;enumeration value="gzCard"/>
 *     &lt;enumeration value="PIDCard"/>
 *     &lt;enumeration value="HISCard"/>
 *     &lt;enumeration value="PatientCard"/>
 *     &lt;enumeration value="CashSaver"/>
 *     &lt;enumeration value="pkg8583"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "device_enum")
@XmlEnum
public enum DeviceEnum {

    @XmlEnumValue("magnetCard")
    MAGNET_CARD("magnetCard"),
    @XmlEnumValue("ICCard")
    IC_CARD("ICCard"),
    @XmlEnumValue("sensorCard")
    SENSOR_CARD("sensorCard"),
    @XmlEnumValue("twoInOneCard")
    TWO_IN_ONE_CARD("twoInOneCard"),
    @XmlEnumValue("printer")
    PRINTER("printer"),
    @XmlEnumValue("keyboard")
    KEYBOARD("keyboard"),
    @XmlEnumValue("gzCard")
    GZ_CARD("gzCard"),
    @XmlEnumValue("PIDCard")
    PID_CARD("PIDCard"),
    @XmlEnumValue("HISCard")
    HIS_CARD("HISCard"),
    @XmlEnumValue("PatientCard")
    PATIENT_CARD("PatientCard"),
    @XmlEnumValue("CashSaver")
    CASH_SAVER("CashSaver"),
    @XmlEnumValue("pkg8583")
    PKG_8583("pkg8583"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    DeviceEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DeviceEnum fromValue(String v) {
        for (DeviceEnum c: DeviceEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
