//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.18 at 11:13:00 AM CST 
//


package king.flow.view;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the king.flow.view package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Window_QNAME = new QName("", "window");
    private final static QName _Panel_QNAME = new QName("", "panel");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: king.flow.view
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link Driver }
     * 
     */
    public Driver createDriver() {
        return new Driver();
    }

    /**
     * Create an instance of {@link MsgSendAction }
     * 
     */
    public MsgSendAction createMsgSendAction() {
        return new MsgSendAction();
    }

    /**
     * Create an instance of {@link Rules }
     * 
     */
    public Rules createRules() {
        return new Rules();
    }

    /**
     * Create an instance of {@link DefinedAction }
     * 
     */
    public DefinedAction createDefinedAction() {
        return new DefinedAction();
    }

    /**
     * Create an instance of {@link DefinedAction.ConstructorParameters }
     * 
     */
    public DefinedAction.ConstructorParameters createDefinedActionConstructorParameters() {
        return new DefinedAction.ConstructorParameters();
    }

    /**
     * Create an instance of {@link Window }
     * 
     */
    public Window createWindow() {
        return new Window();
    }

    /**
     * Create an instance of {@link Panel }
     * 
     */
    public Panel createPanel() {
        return new Panel();
    }

    /**
     * Create an instance of {@link Decorator }
     * 
     */
    public Decorator createDecorator() {
        return new Decorator();
    }

    /**
     * Create an instance of {@link Bound }
     * 
     */
    public Bound createBound() {
        return new Bound();
    }

    /**
     * Create an instance of {@link JumpAction }
     * 
     */
    public JumpAction createJumpAction() {
        return new JumpAction();
    }

    /**
     * Create an instance of {@link BasicAttribute }
     * 
     */
    public BasicAttribute createBasicAttribute() {
        return new BasicAttribute();
    }

    /**
     * Create an instance of {@link Menubar }
     * 
     */
    public Menubar createMenubar() {
        return new Menubar();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link UiStyle }
     * 
     */
    public UiStyle createUiStyle() {
        return new UiStyle();
    }

    /**
     * Create an instance of {@link Menuaction }
     * 
     */
    public Menuaction createMenuaction() {
        return new Menuaction();
    }

    /**
     * Create an instance of {@link Menuoption }
     * 
     */
    public Menuoption createMenuoption() {
        return new Menuoption();
    }

    /**
     * Create an instance of {@link Menuitem }
     * 
     */
    public Menuitem createMenuitem() {
        return new Menuitem();
    }

    /**
     * Create an instance of {@link Font }
     * 
     */
    public Font createFont() {
        return new Font();
    }

    /**
     * Create an instance of {@link Action.SetFontAction }
     * 
     */
    public Action.SetFontAction createActionSetFontAction() {
        return new Action.SetFontAction();
    }

    /**
     * Create an instance of {@link Action.CleanAction }
     * 
     */
    public Action.CleanAction createActionCleanAction() {
        return new Action.CleanAction();
    }

    /**
     * Create an instance of {@link Action.UploadFileAction }
     * 
     */
    public Action.UploadFileAction createActionUploadFileAction() {
        return new Action.UploadFileAction();
    }

    /**
     * Create an instance of {@link Action.MoveCursorAction }
     * 
     */
    public Action.MoveCursorAction createActionMoveCursorAction() {
        return new Action.MoveCursorAction();
    }

    /**
     * Create an instance of {@link Action.LimitInputAction }
     * 
     */
    public Action.LimitInputAction createActionLimitInputAction() {
        return new Action.LimitInputAction();
    }

    /**
     * Create an instance of {@link Action.UseTipAction }
     * 
     */
    public Action.UseTipAction createActionUseTipAction() {
        return new Action.UseTipAction();
    }

    /**
     * Create an instance of {@link Action.ShowTableAction }
     * 
     */
    public Action.ShowTableAction createActionShowTableAction() {
        return new Action.ShowTableAction();
    }

    /**
     * Create an instance of {@link Action.ShowComboBoxAction }
     * 
     */
    public Action.ShowComboBoxAction createActionShowComboBoxAction() {
        return new Action.ShowComboBoxAction();
    }

    /**
     * Create an instance of {@link Action.PlayMediaAction }
     * 
     */
    public Action.PlayMediaAction createActionPlayMediaAction() {
        return new Action.PlayMediaAction();
    }

    /**
     * Create an instance of {@link Action.RunCommandAction }
     * 
     */
    public Action.RunCommandAction createActionRunCommandAction() {
        return new Action.RunCommandAction();
    }

    /**
     * Create an instance of {@link Action.VirtualKeyboardAction }
     * 
     */
    public Action.VirtualKeyboardAction createActionVirtualKeyboardAction() {
        return new Action.VirtualKeyboardAction();
    }

    /**
     * Create an instance of {@link Action.SetPrinterAction }
     * 
     */
    public Action.SetPrinterAction createActionSetPrinterAction() {
        return new Action.SetPrinterAction();
    }

    /**
     * Create an instance of {@link Action.SwipeCardAction }
     * 
     */
    public Action.SwipeCardAction createActionSwipeCardAction() {
        return new Action.SwipeCardAction();
    }

    /**
     * Create an instance of {@link Action.RwFingerPrintAction }
     * 
     */
    public Action.RwFingerPrintAction createActionRwFingerPrintAction() {
        return new Action.RwFingerPrintAction();
    }

    /**
     * Create an instance of {@link Action.WebLoadAction }
     * 
     */
    public Action.WebLoadAction createActionWebLoadAction() {
        return new Action.WebLoadAction();
    }

    /**
     * Create an instance of {@link Action.InsertICardAction }
     * 
     */
    public Action.InsertICardAction createActionInsertICardAction() {
        return new Action.InsertICardAction();
    }

    /**
     * Create an instance of {@link Driver.Device }
     * 
     */
    public Driver.Device createDriverDevice() {
        return new Driver.Device();
    }

    /**
     * Create an instance of {@link MsgSendAction.NextStep }
     * 
     */
    public MsgSendAction.NextStep createMsgSendActionNextStep() {
        return new MsgSendAction.NextStep();
    }

    /**
     * Create an instance of {@link MsgSendAction.Exception }
     * 
     */
    public MsgSendAction.Exception createMsgSendActionException() {
        return new MsgSendAction.Exception();
    }

    /**
     * Create an instance of {@link Rules.NotNull }
     * 
     */
    public Rules.NotNull createRulesNotNull() {
        return new Rules.NotNull();
    }

    /**
     * Create an instance of {@link Rules.ValidateCJK }
     * 
     */
    public Rules.ValidateCJK createRulesValidateCJK() {
        return new Rules.ValidateCJK();
    }

    /**
     * Create an instance of {@link Rules.Template }
     * 
     */
    public Rules.Template createRulesTemplate() {
        return new Rules.Template();
    }

    /**
     * Create an instance of {@link Rules.Equal }
     * 
     */
    public Rules.Equal createRulesEqual() {
        return new Rules.Equal();
    }

    /**
     * Create an instance of {@link Rules.NotEqual }
     * 
     */
    public Rules.NotEqual createRulesNotEqual() {
        return new Rules.NotEqual();
    }

    /**
     * Create an instance of {@link DefinedAction.ConstructorParameters.Parameter }
     * 
     */
    public DefinedAction.ConstructorParameters.Parameter createDefinedActionConstructorParametersParameter() {
        return new DefinedAction.ConstructorParameters.Parameter();
    }

    /**
     * Create an instance of {@link Window.Contents }
     * 
     */
    public Window.Contents createWindowContents() {
        return new Window.Contents();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Window }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "window")
    public JAXBElement<Window> createWindow(Window value) {
        return new JAXBElement<Window>(_Window_QNAME, Window.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Panel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "panel")
    public JAXBElement<Panel> createPanel(Panel value) {
        return new JAXBElement<Panel>(_Panel_QNAME, Panel.class, null, value);
    }

}
