del .\lib\*.*
copy G:\king\apache-maven-3.2.3\repo\org\apache\derby\derby\10.10.2.0\derby-10.10.2.0.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\apache\derby\derbyclient\10.10.2.0\derbyclient-10.10.2.0.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\eclipse\persistence\eclipselink\2.5.1\eclipselink-2.5.1.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\hibernate\hibernate-entitymanager\4.1.8.Final\hibernate-entitymanager-4.1.8.Final.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\hibernate\javax\persistence\hibernate-jpa-2.1-api\1.0.0.Final\hibernate-jpa-2.1-api-1.0.0.Final.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\unknown\binary\hibernate-jpamodelgen-1.3.0.Final\SNAPSHOT\hibernate-jpamodelgen-1.3.0.Final-SNAPSHOT.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\com\jgoodies\jgoodies-looks\2.5.3\jgoodies-looks-2.5.3.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\com\github\jsonj\jsonj\0.8\jsonj-0.8.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\io\netty\netty-all\4.0.4.Final\netty-all-4.0.4.Final.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\eclipse\persistence\org.eclipse.persistence.jpa.modelgen.processor\2.5.1\org.eclipse.persistence.jpa.modelgen.processor-2.5.1.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\swinglabs\swingx\swingx-all\1.6.5-1\swingx-all-1.6.5-1.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\antlr\antlr\2.7.7\antlr-2.7.7.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\eclipse\persistence\commonj.sdo\2.1.1\commonj.sdo-2.1.1.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\commons-lang\commons-lang\2.6\commons-lang-2.6.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\dom4j\dom4j\1.6.1\dom4j-1.6.1.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\hamcrest\hamcrest-core\1.1\hamcrest-core-1.1.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\hibernate\common\hibernate-commons-annotations\4.0.1.Final\hibernate-commons-annotations-4.0.1.Final.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\hibernate\hibernate-core\4.1.8.Final\hibernate-core-4.1.8.Final.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\hibernate\javax\persistence\hibernate-jpa-2.0-api\1.0.1.Final\hibernate-jpa-2.0-api-1.0.1.Final.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\javassist\javassist\3.15.0-GA\javassist-3.15.0-GA.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\eclipse\persistence\javax.persistence\2.1.0\javax.persistence-2.1.0.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\jboss\logging\jboss-logging\3.1.0.GA\jboss-logging-3.1.0.GA.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\jboss\spec\javax\transaction\jboss-transaction-api_1.1_spec\1.0.0.Final\jboss-transaction-api_1.1_spec-1.0.0.Final.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\com\jgoodies\jgoodies-common\1.6.0\jgoodies-common-1.6.0.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\com\googlecode\json-simple\json-simple\1.1.1\json-simple-1.1.1.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\junit\junit\4.10\junit-4.10.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\eclipse\persistence\org.eclipse.persistence.antlr\2.5.1\org.eclipse.persistence.antlr-2.5.1.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\eclipse\persistence\org.eclipse.persistence.asm\2.5.1\org.eclipse.persistence.asm-2.5.1.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\eclipse\persistence\org.eclipse.persistence.core\2.5.1\org.eclipse.persistence.core-2.5.1.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\eclipse\persistence\org.eclipse.persistence.jpa\2.5.1\org.eclipse.persistence.jpa-2.5.1.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\org\eclipse\persistence\org.eclipse.persistence.jpa.jpql\2.5.1\org.eclipse.persistence.jpa.jpql-2.5.1.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\javax\media\jmf\2.1.1e\jmf-2.1.1e.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\net\java\dev\jna\jna\3.2.3\jna-3.2.3.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\natvie\component\DJNativeSwing\SNAPSHOT\DJNativeSwing-SNAPSHOT.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\natvie\component\DJNativeSwing-SWT\SNAPSHOT\DJNativeSwing-SWT-SNAPSHOT.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\natvie\component\MozillaInterfaces-1.8.1.3\SNAPSHOT\MozillaInterfaces-1.8.1.3-SNAPSHOT.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\natvie\component\swt-4.3-win32-win32-x86\SNAPSHOT\swt-4.3-win32-win32-x86-SNAPSHOT.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\commons-io\commons-io\2.4\commons-io-2.4.jar .\lib
copy G:\king\apache-maven-3.2.3\repo\com\google\guava\guava\18.0\guava-18.0.jar .\lib