/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class king_flow_control_driver_TwoInOneCardConductor */

#ifndef _Included_king_flow_control_driver_TwoInOneCardConductor
#define _Included_king_flow_control_driver_TwoInOneCardConductor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     king_flow_control_driver_TwoInOneCardConductor
 * Method:    checkCard
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_king_flow_control_driver_TwoInOneCardConductor_checkCard
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     king_flow_control_driver_TwoInOneCardConductor
 * Method:    readCard
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_king_flow_control_driver_TwoInOneCardConductor_readCard
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
