/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class king_flow_control_driver_HISCardConductor */

#ifndef _Included_king_flow_control_driver_HISCardConductor
#define _Included_king_flow_control_driver_HISCardConductor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     king_flow_control_driver_HISCardConductor
 * Method:    getCard
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_king_flow_control_driver_HISCardConductor_getCard
  (JNIEnv *, jobject, jstring);

/*
 * Class:     king_flow_control_driver_HISCardConductor
 * Method:    ejectCard
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_king_flow_control_driver_HISCardConductor_ejectCard
  (JNIEnv *, jobject, jstring);

/*
 * Class:     king_flow_control_driver_HISCardConductor
 * Method:    withdrawCard
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_king_flow_control_driver_HISCardConductor_withdrawCard
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
