/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class king_flow_control_driver_PrinterConductor */

#ifndef _Included_king_flow_control_driver_PrinterConductor
#define _Included_king_flow_control_driver_PrinterConductor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     king_flow_control_driver_PrinterConductor
 * Method:    print
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_king_flow_control_driver_PrinterConductor_print
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     king_flow_control_driver_PrinterConductor
 * Method:    printState
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_king_flow_control_driver_PrinterConductor_printState
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     king_flow_control_driver_PrinterConductor
 * Method:    printPassBook
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_king_flow_control_driver_PrinterConductor_printPassBook
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
