/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class king_flow_control_driver_MedicareCardConductor */

#ifndef _Included_king_flow_control_driver_MedicareCardConductor
#define _Included_king_flow_control_driver_MedicareCardConductor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     king_flow_control_driver_MedicareCardConductor
 * Method:    runCmd
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_king_flow_control_driver_MedicareCardConductor_runCmd
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
