/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class king_flow_control_driver_PKG8583 */

#ifndef _Included_king_flow_control_driver_PKG8583
#define _Included_king_flow_control_driver_PKG8583
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     king_flow_control_driver_PKG8583
 * Method:    getMac
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_king_flow_control_driver_PKG8583_getMac
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
