/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class king_flow_control_driver_CashConductor */

#ifndef _Included_king_flow_control_driver_CashConductor
#define _Included_king_flow_control_driver_CashConductor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     king_flow_control_driver_CashConductor
 * Method:    readCash
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_king_flow_control_driver_CashConductor_readCash
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     king_flow_control_driver_CashConductor
 * Method:    close
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_king_flow_control_driver_CashConductor_close
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
