/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class king_flow_control_driver_GzCardConductor */

#ifndef _Included_king_flow_control_driver_GzCardConductor
#define _Included_king_flow_control_driver_GzCardConductor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     king_flow_control_driver_GzCardConductor
 * Method:    readCard
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_king_flow_control_driver_GzCardConductor_readCard
  (JNIEnv *, jobject, jint);

/*
 * Class:     king_flow_control_driver_GzCardConductor
 * Method:    writeCard
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_king_flow_control_driver_GzCardConductor_writeCard
  (JNIEnv *, jobject, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
