/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class king_flow_control_driver_PIDCardConductor */

#ifndef _Included_king_flow_control_driver_PIDCardConductor
#define _Included_king_flow_control_driver_PIDCardConductor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     king_flow_control_driver_PIDCardConductor
 * Method:    readCard
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_king_flow_control_driver_PIDCardConductor_readCard
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
