/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class king_flow_control_driver_MagnetCardConductor */

#ifndef _Included_king_flow_control_driver_MagnetCardConductor
#define _Included_king_flow_control_driver_MagnetCardConductor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     king_flow_control_driver_MagnetCardConductor
 * Method:    readCard
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_king_flow_control_driver_MagnetCardConductor_readCard
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
