//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.18 at 04:41:11 PM CST 
//


package king.flow.test.devops.define;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the king.flow.test.devops.define package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Testsuits_QNAME = new QName("", "testsuits");
    private final static QName _Testcase_QNAME = new QName("", "testcase");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: king.flow.test.devops.define
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestStep }
     * 
     */
    public TestStep createTestStep() {
        return new TestStep();
    }

    /**
     * Create an instance of {@link TestCase }
     * 
     */
    public TestCase createTestCase() {
        return new TestCase();
    }

    /**
     * Create an instance of {@link TestSuits }
     * 
     */
    public TestSuits createTestSuits() {
        return new TestSuits();
    }

    /**
     * Create an instance of {@link TestStep.Action }
     * 
     */
    public TestStep.Action createTestStepAction() {
        return new TestStep.Action();
    }

    /**
     * Create an instance of {@link TestCase.Steps }
     * 
     */
    public TestCase.Steps createTestCaseSteps() {
        return new TestCase.Steps();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestSuits }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "testsuits")
    public JAXBElement<TestSuits> createTestsuits(TestSuits value) {
        return new JAXBElement<TestSuits>(_Testsuits_QNAME, TestSuits.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestCase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "testcase")
    public JAXBElement<TestCase> createTestcase(TestCase value) {
        return new JAXBElement<TestCase>(_Testcase_QNAME, TestCase.class, null, value);
    }

}
